version: '2'
services:
  demo-application:
    image: barrycommins/spring-boot-sleuth-splunk-demo
    user: root  # has to run as root user, because it needs to write logs to shared volume
    environment:
      - LOGGING_FILE_NAME=/logs/demo-application.log
    ports:
      - "8080:8080"
    volumes:
      - log_volume:/logs
  splunk:
    image: splunk/splunk:8.0
    hostname: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_PASSWORD=password
    ports:
      - "8000:8000"
  splunkforwarder:
    image: splunk/universalforwarder:8.0
    hostname: splunkforwarder
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes
      - SPLUNK_STANDALONE_URL=splunk:9997
      - SPLUNK_USER=root
      - SPLUNK_ADD=monitor /logs
      - SPLUNK_PASSWORD=password
    restart: always
    depends_on:
      - splunk
    volumes:
      - log_volume:/logs
volumes:
  log_volume: